[package]
name = "ftr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
ansi_term = "0.12"
rust-htslib = "*"
clap = "2.33.3"
needletail = "0.4.1"